/* Automatically generated by wasm2c */
#ifndef W2_H_GENERATED_
#define W2_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_w2 {
  u32 w2c_0x5F_stack_pointer;
  u32 w2c_0x5F_stack_end;
  u32 w2c_0x5F_stack_base;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_w2;

void wasm2c_w2_instantiate(w2c_w2*);
void wasm2c_w2_free(w2c_w2*);
wasm_rt_func_type_t wasm2c_w2_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'memory' */
wasm_rt_memory_t* w2c_w2_memory(w2c_w2* instance);

/* export: '__wasm_call_ctors' */
void w2c_w2_0x5F_wasm_call_ctors(w2c_w2*);

/* export: 'main' */
u32 w2c_w2_main(w2c_w2*, u32, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_w2_0x5F_indirect_function_table(w2c_w2* instance);

/* export: '__errno_location' */
u32 w2c_w2_0x5F_errno_location(w2c_w2*);

/* export: '__stdio_exit' */
void w2c_w2_0x5F_stdio_exit(w2c_w2*);

/* export: 'emscripten_stack_init' */
void w2c_w2_emscripten_stack_init(w2c_w2*);

/* export: 'emscripten_stack_get_free' */
u32 w2c_w2_emscripten_stack_get_free(w2c_w2*);

/* export: 'emscripten_stack_get_base' */
u32 w2c_w2_emscripten_stack_get_base(w2c_w2*);

/* export: 'emscripten_stack_get_end' */
u32 w2c_w2_emscripten_stack_get_end(w2c_w2*);

/* export: 'stackSave' */
u32 w2c_w2_stackSave(w2c_w2*);

/* export: 'stackRestore' */
void w2c_w2_stackRestore(w2c_w2*, u32);

/* export: 'stackAlloc' */
u32 w2c_w2_stackAlloc(w2c_w2*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* W2_H_GENERATED_ */
